{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Release.Name }}-secret
    kind: SecretStore
  target:
    name: device-api-secret
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: device-api/db-password
{{- end }}