apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: telemetry-ingestor
  template:
    metadata:
      labels:
        app: telemetry-ingestor
    spec:
      containers:
      - name: telemetry-ingestor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: 80

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: 80
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}

        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: 80
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}