{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-service-monitor
spec:
  selector:
    matchLabels:
      app: telemetry-ingestor
  endpoints:
  - port: http
    path: /
    interval: 15s
{{- end }}